use_frameworks!

target 'StatableExample' do
	target 'StatableExampleTests' do
	end

	pod 'Statable', :git => 'https://github.com/k-o-d-e-n/Statable.git', :branch => 'pod_install'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end