use_frameworks!

target 'StatableExample' do
	target 'StatableExampleTests' do
	end

	pod 'Statable'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.1'
        end
    end
end
